config/routes.rb
Rails.application.routes.draw do
  resources :listings
  devise_for :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  root 'pages#explore'
  
  get '/join' => 'pages#index'
  get '/user/:id' => 'pages#profile'

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :listing
  attachment :file
end

app/models/listing.rb
class Listing < ActiveRecord::Base
    belongs_to :user
    has_many :images, dependent: :destroy
    accepts_attachments_for :images, attachment: :file, append: true
    validates :user_id, presence: true
    default_scope -> { order(created_at: :desc) }
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         has_many :posts, dependent: :destroy # remove a user's posts if his account is deleted.
         has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
         has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
         
         has_many :following, through: :active_relationships, source: :followed
         has_many :followers, through: :passive_relationships, source: :follower
         
         
         # helper methods
         
         # follow another user
         def follow(other)
           active_relationships.create(followed_id: other.id)
         end
         
         # unfollow a user
         def unfollow(other)
           active_relationships.find_by(followed_id: other.id).destroy
         end
         
         # is following a user?
         def following?(other)
           following.include?(other)
         end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # call the configured param
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  # protect the database
  protected 
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit( :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit( :email, :current_password, :password, :password_confirmation, :remember_me) }
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to "/user/" + current_user.username, notice: 'Listing was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        f.html { redirect_to "/user/" + current_user.username, notice: "Listing was successfully updated!" }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      f.html { redirect_to "/user/" + current_user.username, notice: "Post Deleted!" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :year, :make, :model, :model_detail, :kilometres, :ext_colout, :int_colour, :no_doors, :body_style, :fuel_type, :cylinders, :engine_size, :transmission, :off_road, :no_owners, :import_history, :rego_expiry, :wof_expiry, :no_plate, :aa_inspection, :stereo_descripton, :abs_brakes, :air_con, :alarm, :alloy_wheels, :central_locking, :driver_airbag, :passenger_airbag, :power_steering, :sunroof, :towbar, :description, images_files: [])
    end
end

app/controllers/pages_controller.rb
# THe pages controller contains all of the code for any page inside /pages
class PagesController < ApplicationController
  def index
  end

  def explore
    if current_user != nil
      @followers_count = current_user.followers.count
      @following_count = current_user.following.count
      @user_posts = Listing.all.where("user_id = ?", current_user.id)
      @user_posts_count = @user_posts.length
      @username = current_user.username
    else
      redirect_to '/join/'
    end
    
    @posts = Listing.all
    @posts_count = @posts.length
    
    @newPost = Listing.new
  end

  def profile
    if(User.find_by_username(params[:id]))
      @username = params[:id]
      
      @followers_count = User.find_by_username(@username).followers.count
      @following_count = User.find_by_username(@username).following.count
        
      @posts = Listing.all.where("user_id = ?", User.find_by_username(@username).id)
      @posts_count = @posts.length
      @newPost = Listing.new
    else
      redirect_to '/explore/', :notice=> "User not found!"
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    
    def create
        user = User.find(params[:followed_id])
        current_user.follow(user)
        redirect_to(:back)
    end
    
    def destroy
        user = Relationship.find(params[:id]).followed 
        current_user.unfollow(user)
        redirect_to(:back)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<% if !user_signed_in? %>
  <%= render '/layouts/footer_guest' %>
<% else %>
  <%= render '/layouts/footer_user' %>
<% end %>

app/views/layouts/_footer_guest.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
        <li><a href="/explore">Explore</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to('Sign up', new_user_registration_path) %></li>
        <li><%= link_to('Login', new_user_session_path) %></li>
        <li><a href="#">Help</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_footer_user.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
        <li><a href="/explore">Explore</a></li>
        <li><a href="/">Notifications</a></li>
        <li><a href="/">Messages</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/user/<%= current_user.username %>">Profile</a></li>
        <li><a href="#">Help</a></li>
        <li><%= link_to('Settings', edit_user_registration_path) %></li>
        <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_nav.html.erb
<% if !user_signed_in? %>
  <%= render '/layouts/nav_guest' %>
<% else %>
  <%= render '/layouts/nav_user' %>
<% end %>

app/views/layouts/_nav_guest.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to('Sign up', new_user_registration_path) %></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to('Login', new_user_session_path) %></li>
        <li role="separator" class="divider"></li>
        <li><a href="#">Help</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_nav_user.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">Explore</a></li>
        <li><a href="/">Notifications</a></li>
        <li><a href="/">Messages</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search Flutter">
            </div>
          </form>
        </li>
                
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><img class="rounded-img" src="/avatar.png" height="25px" /><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/user/<%= current_user.username %>">Profile</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Help</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to('Settings', edit_user_registration_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
          </ul>
        </li>
        <li><a id="new-listing-btn" class="btn btn-primary navbar-btn" href="/listings/new"><i class="fa fa-car" aria-hidden="true"></i> sellacar</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flutter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<%= render '/layouts/nav' %>

<% if params[:id] != nil %>
  <% @url = '/user/' + params[:id] %>
  <% if current_page?(@url) %>
    <div class="row hidden-xs">
      <div class="col-xs-12">
        <div class="jumbotron margin-0 profile-banner"></div>
      </div>
    </div>
    <div class="row hidden-xs">
        <nav class="navbar navbar-default margin-bottom-0">
          <div class="container-fluid container">
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="col-xs-12 col-sm-9 col-sm-offset-3">
              <center>
              <ul class="nav navbar-nav">
                <li><a class="padding-0 padding-right-25" href="">
                  <h6 class="opacity-7 font-size-10">LISTINGS</h6>
                  <h6 class="blue-text font-size-18 opacity-7"><%= @posts_count %></h6>
                </a></li>
                <li><a class="padding-0 padding-right-25" href="/home">
                  <h6 class="opacity-7 font-size-10">FOLLOWERS</h6>
                  <h6 class="blue-text font-size-18 opacity-7"><%= @followers_count %></h6>
                </a></li>
                <li><a class="padding-0 padding-right-25" href="/home">
                  <h6 class="opacity-7 font-size-10">FOLLOWING</h6>
                  <h6 class="blue-text font-size-18 opacity-7"><%= @following_count %></h6>
                </a></li>
              </ul>
              </center>
              <% if current_user != nil %>
              <% @profile = params[:id] %>
              <% if @profile != current_user.username %>
              <ul class="nav navbar-nav navbar-right margin-top-12-5">
                <li><%= render '/components/follow_button', :user => User.find_by_username(params[:id]) %></li>
              </ul>
              <% end %>
              <% end %>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
    </div>
  <% end %>
<% end %>
<div id="content" class="container">
  <% if notice != nil %>
  <div class="notice">
    <strong><%= notice %></strong>
  </div>
  <% end %>
  <% if alert != nil %>
  <div class="notice notice-warning">
    <strong><%= alert %></strong>
  </div>
  <% end %>
  <%= yield %>
</div>

<footer class="row hidden-xs">
    <%= render '/layouts/footer' %>
</footer>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">sellacar</h4>
      </div>
      <div class="modal-body">
        <div class="stepwizard">
          <div class="stepwizard-row setup-panel">
              <div class="stepwizard-step">
                  <a href="#step-1" type="button" class="btn btn-primary btn-circle">1</a>
                  <p>Details</p>
              </div>
              <div class="stepwizard-step">
                  <a href="#step-2" type="button" class="btn btn-default btn-circle" disabled="disabled">2</a>
                  <p>Photos</p>
              </div>
              <div class="stepwizard-step">
                  <a href="#step-3" type="button" class="btn btn-default btn-circle" disabled="disabled">3</a>
                  <p>Confirm</p>
              </div>
          </div>
      </div>
      <form role="form">
          <div class="row setup-content" id="step-1">
              <div class="col-xs-12">
                  <div class="col-md-12">
                      <div class="form-group">
                          <label class="control-label">First Name</label>
                          <input  maxlength="100" type="text" required="required" class="form-control" placeholder="Enter First Name"  />
                      </div>
                      <div class="form-group">
                          <label class="control-label">Last Name</label>
                          <input maxlength="100" type="text" required="required" class="form-control" placeholder="Enter Last Name" />
                      </div>
                      <button class="btn btn-primary nextBtn pull-right" type="button" >Next</button>
                  </div>
              </div>
          </div>
          <div class="row setup-content" id="step-2">
              <div class="col-xs-12">
                  <div class="col-md-12">
                      <div class="form-group">
                          <label class="control-label">Company Name</label>
                          <input maxlength="200" type="text" required="required" class="form-control" placeholder="Enter Company Name" />
                      </div>
                      <div class="form-group">
                          <label class="control-label">Company Address</label>
                          <input maxlength="200" type="text" required="required" class="form-control" placeholder="Enter Company Address"  />
                      </div>
                      <button class="btn btn-primary nextBtn pull-right" type="button" >Next</button>
                  </div>
              </div>
          </div>
          <div class="row setup-content" id="step-3">
              <div class="col-xs-12">
                  <div class="col-md-12">
                      <button class="btn btn-success pull-right" type="submit">Finish!</button>
                  </div>
              </div>
          </div>
      </form>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<!--<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Year</th>
      <th>Make</th>
      <th>Model</th>
      <th>Model detail</th>
      <th>Kilometres</th>
      <th>Ext colout</th>
      <th>Int colour</th>
      <th>No doors</th>
      <th>Body style</th>
      <th>Fuel type</th>
      <th>Cylinders</th>
      <th>Engine size</th>
      <th>Transmission</th>
      <th>4wd</th>
      <th>No owners</th>
      <th>Import history</th>
      <th>Rego expiry</th>
      <th>Wof expiry</th>
      <th>No plate</th>
      <th>Aa inspection</th>
      <th>Stereo descripton</th>
      <th>Abs brakes</th>
      <th>Air con</th>
      <th>Alarm</th>
      <th>Alloy wheels</th>
      <th>Central locking</th>
      <th>Driver airbag</th>
      <th>Passenger airbag</th>
      <th>Power steering</th>
      <th>Sunroof</th>
      <th>Towbar</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.title %></td>
        <td><%= listing.year %></td>
        <td><%= listing.make %></td>
        <td><%= listing.model %></td>
        <td><%= listing.model_detail %></td>
        <td><%= listing.kilometres %></td>
        <td><%= listing.ext_colout %></td>
        <td><%= listing.int_colour %></td>
        <td><%= listing.no_doors %></td>
        <td><%= listing.body_style %></td>
        <td><%= listing.fuel_type %></td>
        <td><%= listing.cylinders %></td>
        <td><%= listing.engine_size %></td>
        <td><%= listing.transmission %></td>
        <td><%= listing.off_road %></td>
        <td><%= listing.no_owners %></td>
        <td><%= listing.import_history %></td>
        <td><%= listing.rego_expiry %></td>
        <td><%= listing.wof_expiry %></td>
        <td><%= listing.no_plate %></td>
        <td><%= listing.aa_inspection %></td>
        <td><%= listing.stereo_descripton %></td>
        <td><%= listing.abs_brakes %></td>
        <td><%= listing.air_con %></td>
        <td><%= listing.alarm %></td>
        <td><%= listing.alloy_wheels %></td>
        <td><%= listing.central_locking %></td>
        <td><%= listing.driver_airbag %></td>
        <td><%= listing.passenger_airbag %></td>
        <td><%= listing.power_steering %></td>
        <td><%= listing.sunroof %></td>
        <td><%= listing.towbar %></td>
        <td><%= listing.description %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>-->
<% for @p in @listings %>
      <% @username = User.find_by_id(@p.user_id).username %>
      <div class="panel panel-default post-panel">
        <div class="panel-body">
          <div class="col-xs-1 padding-0">
            <img class="rounded-img" src="avatar.png" width="100%" />
          </div>
          <div class="col-xs-11">
            <p class="post-title"><span class="post-owner"><a href="/user/<%= @username %>"><%= @username %></a></span><span class="post-creation"> - <%= @p.created_at.to_formatted_s(:short) %></p>
            <p class="post-content"><%= @p.description %></p>
          </div>
          <div class="row">
            <div class="col-xs-12">
              <p class="post-links">
                <span class="glyphicon glyphicon-comment g-links" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-retweet g-links" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-heart g-links" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-option-horizontal g-links" aria-hidden="true"></span>
                <a href="/listings/<%= @p.id %>">View listing</a>
              </p>
            </div>
          </div>
          
        </div>
      </div>
      <% end %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <% @listing.images.each do |i| %>
    <%= attachment_image_tag(i, :file, format: "jpg") %>
  <% end %>
</p>
<p>
  <strong>Title:</strong>
  <%= @listing.title %>
</p>

<p>
  <strong>Year:</strong>
  <%= @listing.year %>
</p>

<p>
  <strong>Make:</strong>
  <%= @listing.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @listing.model %>
</p>

<p>
  <strong>Model detail:</strong>
  <%= @listing.model_detail %>
</p>

<p>
  <strong>Kilometres:</strong>
  <%= @listing.kilometres %>
</p>

<p>
  <strong>Ext colout:</strong>
  <%= @listing.ext_colout %>
</p>

<p>
  <strong>Int colour:</strong>
  <%= @listing.int_colour %>
</p>

<p>
  <strong>No doors:</strong>
  <%= @listing.no_doors %>
</p>

<p>
  <strong>Body style:</strong>
  <%= @listing.body_style %>
</p>

<p>
  <strong>Fuel type:</strong>
  <%= @listing.fuel_type %>
</p>

<p>
  <strong>Cylinders:</strong>
  <%= @listing.cylinders %>
</p>

<p>
  <strong>Engine size:</strong>
  <%= @listing.engine_size %>
</p>

<p>
  <strong>Transmission:</strong>
  <%= @listing.transmission %>
</p>

<p>
  <strong>4wd:</strong>
  <%= @listing.off_road %>
</p>

<p>
  <strong>No owners:</strong>
  <%= @listing.no_owners %>
</p>

<p>
  <strong>Import history:</strong>
  <%= @listing.import_history %>
</p>

<p>
  <strong>Rego expiry:</strong>
  <%= @listing.rego_expiry %>
</p>

<p>
  <strong>Wof expiry:</strong>
  <%= @listing.wof_expiry %>
</p>

<p>
  <strong>No plate:</strong>
  <%= @listing.no_plate %>
</p>

<p>
  <strong>Aa inspection:</strong>
  <%= @listing.aa_inspection %>
</p>

<p>
  <strong>Stereo descripton:</strong>
  <%= @listing.stereo_descripton %>
</p>

<p>
  <strong>Abs brakes:</strong>
  <%= @listing.abs_brakes %>
</p>

<p>
  <strong>Air con:</strong>
  <%= @listing.air_con %>
</p>

<p>
  <strong>Alarm:</strong>
  <%= @listing.alarm %>
</p>

<p>
  <strong>Alloy wheels:</strong>
  <%= @listing.alloy_wheels %>
</p>

<p>
  <strong>Central locking:</strong>
  <%= @listing.central_locking %>
</p>

<p>
  <strong>Driver airbag:</strong>
  <%= @listing.driver_airbag %>
</p>

<p>
  <strong>Passenger airbag:</strong>
  <%= @listing.passenger_airbag %>
</p>

<p>
  <strong>Power steering:</strong>
  <%= @listing.power_steering %>
</p>

<p>
  <strong>Sunroof:</strong>
  <%= @listing.sunroof %>
</p>

<p>
  <strong>Towbar:</strong>
  <%= @listing.towbar %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<% if current_user != nil %><% if current_user.id == @listing.user_id %> <%= link_to 'Edit', edit_listing_path(@listing) %> | <% end %><% end %>
<%= link_to 'Back', :back %>

app/views/pages/index.html.erb
<% if !user_signed_in? %>
    <style>
        body {
            background: linear-gradient(
                rgba(0,0,0,0.7),
                rgba(0,0,0,0.7),
                rgba(0,0,0,0.7)), url("/bg.jpg") no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
        
        h1 {
            color: #ffffff;
            font-weight: bold;
        }
        
        .container-index {
            margin-right: 15%;
            margin-left: 15%;
        }
        
        .text {
            color: #ffffff;
            font-weight: 500;
            font-size: 130%;
        }
        
        .footer-links {
            text-align: center;
            color: #ffffff;
            position: absolute;
            font-size: 10px;
        }
        
        .log-in {
            margin-top: 25px;
            float: right;
            width: 200px;
            height: 175px;
        }
        
        .sign-up {
            float: right;
            width: 200px;
            height: 200px;
            margin-bottom: 100px;
        }
    </style>
    
    <div class="container-index row">
        <div class="col-sm-6">
            <h1>Welcome to Flutter.</h1>
            <p class="text">
                Connect with your buddies. Chat with new friends. <br /> 
                Share your adventures. Have fun! <br />
                Just like a blog, but with less characters.
            </p>
        </div>
        
        <div class="col-sm-6">
            <div class="log-in panel">
            
            </div>
            
            <div class="sign-up panel">
                
            </div>
        </div>
        
    </div>
    
<% else %>
    <script>//document.location = '/explore';</script>
<% end %>